export const LOCATION_UNDERSTANDING_RULE =
  'Understand the whole document BEFORE filling fields. Establish the real-world shooting day, unit, project and physical sites from the header, schedule, maps, movement instructions and later-page references together. Distinguish the fictional story setting from the actual filming place: a scene heading or a character journey is not by itself a crew destination. Relate every relevant scene to its governing site or to an explicit unresolved site; do not silently omit a possible independent filming place just because its address is absent. Reconcile the resulting sites against the whole day, then emit them in the order the document establishes. These are reading steps within ONE response, not separate requests or a transcript of your reasoning. siteEvidence is a short factual source reference (pages/sections and their relationship), not private reasoning.';

export const LOCATION_ROLE_RULE = 'Classify each block by its governing context: filming for an explicitly physical filming set (including equivalent context without a printed label), logistics for support addresses, other for contacts or non-destinations, uncertain only when there is a concrete conflict about filming use. Explain an uncertain role in reviewReason. A place name such as Hospital does not override an explicit filming context. Never infer filming merely because an address exists.';

// Shared by the prompt and structured-output schema: collection is not route selection.
export const LOCATION_COLLECTION_RULE =
  'Return the distinct physical sites established by this whole-document reading, including separately identified logistics for exclusion. Do not scan mechanically for address-shaped strings or enumerate contact lists, equipment, toilets, protocols, map legends and every scene row. For repeated mentions of the SAME site, assemble its associated evidence across pages into ONE location, keeping its governing printed label and recording associated aliases in siteEvidence. Never generate permutations of its venue, street, postcode, access notes or Maps link. Preserve genuinely different sites and different street numbers. A support address next to a site may belong only to parking or access; adjacency does not make it the filming address.';

export const LOCATION_LABEL_RULE =
  'Copy the section label exactly as printed (MOTIV, SET, LOCATION, DREHORT, BASIS, PARKEN, CATERING, etc.). Leave it empty if no label is printed. Never relabel logistics as filming.';

export const LOCATION_DESTINATION_RULE =
  'Only physical filming locations identified by MOTIV, SET, LOCATION, DREHORT or equivalent shooting context are eligible trip destinations. Logistics are collected separately for future features, not used as filming destinations. More than one filming location is valid for the same shooting day.';

export const LOCATION_DAY_RULE =
  'First identify the main shooting date printed on the FIRST PAGE of this callsheet, not its file creation, upload, issue or revision date. This first-page shooting date is the reference for document_day throughout ALL pages. A location need not repeat that date: inherit it from the governing shooting-day context unless an explicit different day applies. Never select the reference date from a later-page preview. For each location, determine the day from its own block, enclosing heading, table column and cross-references. dayScope is document_day only with clear evidence that it belongs to that shooting day; other_day for previous/future days; uncertain when ambiguous. Never inherit the main date across an explicit other-day heading. Include all filming locations for the document day, not just the first.';

export const LOCATION_UNIT_RULE =
  'Determine the filming unit from the governing document header, section, column and cross-references, not from an address or crew contact. Use the unit governing THIS document: a callsheet dedicated to second unit is valid for that unit, not an excluded document. documentUnit is main_unit, other_unit (dedicated second/additional unit), mixed, unspecified or uncertain. For each location unitScope is main_unit, other_unit, unspecified (inherits the governing document unit) or uncertain (a concrete unresolved conflict). In a mixed main/second-unit document retain the main schedule and identify separately the explicitly other-unit blocks. A document without unit labels remains eligible; absence of a unit label is not a reason to reject it.';

export const LOCATION_KIND_RULE = "Distinguish physical destinations from internal markers and moving scenes using the whole document, in ANY language or layout. Rooms, courts, camera positions and lettered subareas inside a governing site are internal_marker, even when headed LOCATION or SET. A vehicle scene or fictional journey without an independent real-world filming site is mobile_scene, not an empty destination; explaining that such a scene has no independent site is not a review conflict. If the document supplies a real filming site for it, use that site's physical_destination instead. A named park, theatre, studio or separately visited building remains a physical_destination even without a street address. Resolve aliases by layout and cross-references; never guess that two sites are the same to eliminate missing data. If a scene might establish another physical site and the document does not resolve it, use locationKind=uncertain (not mobile_scene), retain the printed evidence and explain the specific conflict.";
