export function buildUniversalExtractorPrompt(text: string) {
  return [
    "You are a structured-data extractor for film/TV call sheets (Drehplan / Tagesdispo).",
    "Return a single valid JSON object. No markdown, no explanations.",
    "",
    "── date ──",
    "Main shooting day date from the document header. Normalize to YYYY-MM-DD.",
    "Ignore prep, wrap, or next-day dates.",
    "",
    "── projectName ──",
    "The SHOW/FILM/SERIES TITLE being produced (e.g. 'Dark', 'Tatort', 'Babylon Berlin').",
    "WHERE TO FIND IT:",
    "  • Largest/most prominent text in header (top of document).",
    "  • After labels: 'Projekt:', 'Serie:', 'Film:', 'Titel:', 'Title:', 'Arbeitstitel:', 'AT:'.",
    "  • Near episode info: 'Folge 3' or 'Episode 5' — the name BEFORE or ABOVE it is the project.",
    "WHAT IT IS NOT:",
    "  • Production company (has GmbH/LLC/Ltd/AG/Productions/Film/Pictures in name) → goes in productionCompanies.",
    "  • Document type: 'Drehplan', 'Call Sheet', 'Tagesdisposition', 'Dispo'.",
    "  • Day number: 'DT8', 'Drehtag 5'.",
    "Fallback only if truly nothing found: 'Untitled Project'.",
    "",
    "── productionCompanies ──",
    "Production companies/studios making the show.",
    "WHERE TO FIND IT:",
    "  • After 'Produktion:', 'Production:', 'Herstellung:', labels.",
    "  • Names with GmbH, LLC, Ltd, AG, Productions, Film, Pictures, Entertainment, Studios.",
    "  • Logos in header/footer, copyright lines.",
    "Empty array [] if none found.",
    "",
    "── locations (CRITICAL) ──",
    "ONLY addresses where the CAMERA FILMS (Drehort / Set / Motiv).",
    "Look for labels: 'Drehort', 'Location', 'Set', 'Motiv', 'Filming Location', 'Drehlocation'.",
    "",
    "⛔ NEVER include addresses from these sections (these are logistics, NOT filming):",
    "  Unit Base, Basecamp, Base, Basiscamp, Basis, Sammelpunkt, Treffpunkt,",
    "  Parking, Crew Parking, Parken, Tech Parking,",
    "  Catering, Lunch, Frühstück, Breakfast, Mittagessen,",
    "  Maske, Makeup, Hair, HMU, Garderobe, Wardrobe, Kostüm,",
    "  Production Office, Produktionsbüro, Office, Büro,",
    "  Load & Unload, Laderampe, Anlieferung,",
    "  Hospital, Arzt, Medic.",
    "If a section/row has any of these labels, SKIP its address completely.",
    "",
    "VERBATIM RULE:",
    "• Copy addresses EXACTLY as written in the document.",
    "• NEVER invent, complete, or guess addresses from your knowledge.",
    "• If venue has no street: return 'VenueName, City'.",
    "• If no filming location found: return [\"No location found\"].",
    "",
    "BUILDINGS: Return building name + address. NOT sub-rooms inside (Foyer, Bar, Keller).",
    "",
    "SCOPE: Only today's main unit. Ignore NEXT DAY / NÄCHSTER DREHTAG sections.",
    "",
    "CONTENT TO ANALYZE:",
    "",
    text
  ].join("\n");
}

export function buildCrewFirstDirectPrompt(text: string) {
   return [
    "Extrae datos de esta hoja de rodaje en JSON. Devuelve SOLO JSON válido, sin markdown ni explicaciones.",
    "",
    "CAMPOS CLAVE (diferéncialos correctamente):",
    "• projectName (REQUERIDO): Título del proyecto. Ej: 'Dark', 'El Reino', 'Succession'. NO es la productora.",
    "• productionCompany (opcional): Empresa productora. Ej: 'Netflix', 'Warner Bros', 'UFA Fiction'.",
    "• motiv (opcional): Locación narrativa/escena. Ej: 'Höhle', 'Casa de María - Interior'. NO es dirección física.",
    "• episode (opcional): Número/título episodio. Ej: 'Folge 3', 'EP101'.",
    "• shootingDay (opcional): Día de rodaje. Ej: 'DT8', 'Día 15'.",
    "• generalCallTime (opcional): Hora de llamada en HH:MM.",
    "• date (REQUERIDO): Fecha en YYYY-MM-DD.",
    "",
    "UBICACIONES - Solo incluye estas 7 categorías con dirección física:",
    "1. FILMING_PRINCIPAL - Set principal",
    "2. UNIT_BASE - Basecamp",
    "3. CATERING - Catering",
    "4. MAKEUP_HAIR - Maquillaje/peluquería",
    "5. WARDROBE - Vestuario",
    "6. CREW_PARKING - Parking equipo",
    "7. LOAD_UNLOAD - Carga/descarga",
    "",
    "Por cada ubicación:",
    "• location_type: Una de las 7 categorías",
    "• address (REQUERIDO): Dirección física original",
    "• formatted_address: Dirección normalizada para Google Maps (null si no puedes)",
    "• latitude/longitude: Coordenadas GPS (null si no puedes)",
    "• notes: Max 2 notas logísticas (horarios, trailers, etc)",
    "• confidence: 0-1",
    "",
    "REGLAS:",
    "- version debe ser 'parser-crew-1'",
    "- rutas debe ser []",
    "- Ignora hospitales, protocolos, políticas, teléfonos",
    "- Si solo hay título, deja productionCompany y motiv como null",
    "",
    "EJEMPLO:",
    "Input: 'DARK - Folge 3 - Produktion: Wiedemann & Berg - Motiv: Höhle'",
    "Output: {\"version\":\"parser-crew-1\",\"projectName\":\"Dark\",\"productionCompany\":\"Wiedemann & Berg\",\"motiv\":\"Höhle\",\"episode\":\"Folge 3\",...}",
    "",
    "TEXTO:",
    text
  ].join("\n");
}
