export function buildUniversalExtractorPrompt(text: string) {
  return [
    "You are a structured-data extractor for film/TV call sheets (Drehplan / Tagesdispo).",
    "Return a single valid JSON object. No markdown, no explanations.",
    "",
    "── date ──",
    "Main shooting day date from the document header. Normalize to YYYY-MM-DD.",
    "Ignore prep, wrap, or next-day dates.",
    "",
    "── projectName ──",
    "Creative title of the show/film/series (e.g. 'Dark', 'Succession').",
    "Look in header, 'Projekt:'/'Title:'/'Serie:' labels, repeating header text.",
    "NOT the production company. Remove legal suffixes (GmbH, LLC). Fallback: 'Untitled Project'.",
    "",
    "── productionCompanies ──",
    "All production companies/studios. Look in header, footer, logos, copyright, 'Produktion:' labels.",
    "Empty array [] if none found.",
    "",
    "── locations (CRITICAL) ──",
    "Main filming locations ONLY. Return addresses/venue names EXACTLY as written in the document.",
    "",
    "VERBATIM RULE — absolute constraint:",
    "• Every street, number, and postal code you return MUST appear in the source document.",
    "• NEVER add information from your own knowledge (no completing addresses, no guessing postal codes).",
    "• If only a venue name exists without street: return 'VenueName, City' (city from document context).",
    "• Prefer incomplete-but-real over complete-but-invented.",
    "• If no filming location found: return [\"No location found\"].",
    "",
    "EXCLUDE (not filming locations):",
    "Basecamp/Base, Parking, Catering/Lunch, Production Office, Makeup/Hair/Wardrobe, Load&Unload, Hospital.",
    "",
    "BUILDINGS: Return only the building name + address, not sub-locations inside it.",
    "  ✓ 'Le Meridien, Wien' — the building    ✗ 'You Bar' — a bar inside the hotel",
    "  ✓ 'Hotel Imperial, Kärntner Ring 16, 1010 Wien'    ✗ 'Foyer', 'Keller', 'Stock -1'",
    "",
    "SCOPE: Only today's main unit. Ignore NEXT DAY / NÄCHSTER DREHTAG / FOLGETAG sections.",
    "Ignore 2ND UNIT / DRONE UNIT / B-UNIT locations.",
    "",
    "Multiple filming locations in one day: include all.",
    "",
    "EXAMPLES:",
    "  Doc says 'Drehort: Stephansplatz' (no number) → [\"Stephansplatz, Wien\"]",
    "  Doc says 'Location: Hotel Imperial, Kärntner Ring 16, 1010 Wien' → [\"Hotel Imperial, Kärntner Ring 16, 1010 Wien\"]",
    "  Doc says '@Le Meridien' with scenes in Foyer, Bar → [\"Le Meridien, Wien\"]",
    "  Doc says '13. Erzbischofgasse 6C' → [\"13. Erzbischofgasse 6C\"] (copy verbatim, do not reformat)",
    "",
    "CONTENT TO ANALYZE:",
    "",
    text
  ].join("\n");
}

export function buildCrewFirstDirectPrompt(text: string) {
   return [
    "Extrae datos de esta hoja de rodaje en JSON. Devuelve SOLO JSON válido, sin markdown ni explicaciones.",
    "",
    "CAMPOS CLAVE (diferéncialos correctamente):",
    "• projectName (REQUERIDO): Título del proyecto. Ej: 'Dark', 'El Reino', 'Succession'. NO es la productora.",
    "• productionCompany (opcional): Empresa productora. Ej: 'Netflix', 'Warner Bros', 'UFA Fiction'.",
    "• motiv (opcional): Locación narrativa/escena. Ej: 'Höhle', 'Casa de María - Interior'. NO es dirección física.",
    "• episode (opcional): Número/título episodio. Ej: 'Folge 3', 'EP101'.",
    "• shootingDay (opcional): Día de rodaje. Ej: 'DT8', 'Día 15'.",
    "• generalCallTime (opcional): Hora de llamada en HH:MM.",
    "• date (REQUERIDO): Fecha en YYYY-MM-DD.",
    "",
    "UBICACIONES - Solo incluye estas 7 categorías con dirección física:",
    "1. FILMING_PRINCIPAL - Set principal",
    "2. UNIT_BASE - Basecamp",
    "3. CATERING - Catering",
    "4. MAKEUP_HAIR - Maquillaje/peluquería",
    "5. WARDROBE - Vestuario",
    "6. CREW_PARKING - Parking equipo",
    "7. LOAD_UNLOAD - Carga/descarga",
    "",
    "Por cada ubicación:",
    "• location_type: Una de las 7 categorías",
    "• address (REQUERIDO): Dirección física original",
    "• formatted_address: Dirección normalizada para Google Maps (null si no puedes)",
    "• latitude/longitude: Coordenadas GPS (null si no puedes)",
    "• notes: Max 2 notas logísticas (horarios, trailers, etc)",
    "• confidence: 0-1",
    "",
    "REGLAS:",
    "- version debe ser 'parser-crew-1'",
    "- rutas debe ser []",
    "- Ignora hospitales, protocolos, políticas, teléfonos",
    "- Si solo hay título, deja productionCompany y motiv como null",
    "",
    "EJEMPLO:",
    "Input: 'DARK - Folge 3 - Produktion: Wiedemann & Berg - Motiv: Höhle'",
    "Output: {\"version\":\"parser-crew-1\",\"projectName\":\"Dark\",\"productionCompany\":\"Wiedemann & Berg\",\"motiv\":\"Höhle\",\"episode\":\"Folge 3\",...}",
    "",
    "TEXTO:",
    text
  ].join("\n");
}
